import '../styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body style={{fontFamily: "PlusJakartaSans-Regular", color: "#1C3C50", fontSize: 15.3}}>{children}</body>
    </html>
  )
}
